### ISSUE TITLE
Multiple Threads break SetIterateUpperBound

### ISSUE THREAD

**Issue by danielcrabtree** [warrenfalk/rocksdb-sharp#20] opened 2017-06-23 12:39 UTC
SetIterateUpperBound does not seem to be enforced correctly when there are multiple iterators being used concurrently on the same database.

To test, I created a small program that seems to demonstrate the issue. This test creates a database containing essentially 5 values: 5, 6, 7, 8, 9. It then runs many tasks, which each separately iterate between 6 and 8, which should mean iterating over the values 6 and 7 count many times.

I have made the values multiple bytes, as the bug didn't seem to surface using single byte keys. I haven't been able to observe the bug with just a single task / thread either.

If the test operates correctly, you should see Running followed by Done. If it prints any numbers out, it has failed. 

You may need to run the test numerous times to see a failure. You can also try changing the number of tasks and number of iterations and try changing between debug and release builds. Merely increasing the number of tasks / iterations significantly does not help, as the errors tend to occur near the start of execution.

I've put the test into a loop so you can run it multiple times without restarting it. Just press ENTER to start a test round. Once it is complete, you can press ENTER to start the next round of testing.

**Don't run this code if you have important files in the directory: `C:/TempRock/`. It will be deleted.**

```
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using RocksDbSharp;

namespace Experiments
{
    public class Program
    {
        static void Main(string[] args)
        {
            while(true)
            {
                Directory.Delete("C:/TempRock/", true);

                Console.Out.WriteLine("Ready (press ENTER to start test)");

                Console.In.ReadLine();

                var options = new DbOptions()
                    .SetCreateIfMissing(true);

                using(var db = RocksDb.Open(options, "C:/TempRock/"))
                {
                    var v5 = value(5);
                    var v6 = value(6);
                    var v7 = value(7);
                    var v8 = value(8);
                    var v9 = value(9);

                    db.Put(v5, v5);
                    db.Put(v6, v6);
                    db.Put(v7, v7);
                    db.Put(v8, v8);
                    db.Put(v9, v9);

                    var start = v6;
                    var end = v8;

                    var tasks = Enumerable
                        .Repeat(1, 19)
                        .Select(i => Task.Run(() => iterate(db, start, end, 110_000)))
                        .ToArray();

                    Console.Out.WriteLine("Running");

                    Task.WaitAll(tasks);

                    Console.Out.WriteLine("Done");
                }
            }
        }

        static byte[] value(byte number)
        {
            return new byte[] { 1, 2, number, 4 };
        }

        static void iterate(RocksDb db, byte[] start, byte[] end, int count)
        {
            for(int i = 0; i < count; i++)
            {
                using(var iterator = db.NewIterator(
                    readOptions: new ReadOptions().SetIterateUpperBound(end)))
                {
                    iterator.Seek(start);

                    while(iterator.Valid())
                    {
                        var v = (int)iterator.Key()[2];
                        
                        if(v != 6 && v != 7)
                        {
                            Console.Out.WriteLine(v);
                        }

                        iterator.Next();
                    }
                }
            }
        }
    }
}
```

**Comment by danielcrabtree** [comment] 2017-06-23 13:15
I think the problem might be that the methods which take byte[] instead of byte* do not pin the memory.

I've modified the iterate method to pin the memory used by SetIterateUpperBound and Seek and so far, haven't seen the bug. I will continue testing to see if the bug occurs, or if this is the solution.

```
static unsafe void iterate(RocksDb db, byte[] start, byte[] end, int count)
{
    for(int i = 0; i < count; i++)
    {
        ulong sl = (ulong)start.LongLength;
        ulong el = (ulong)end.LongLength;

        fixed (byte* pStart = start, pEnd = end)
        {
            byte* ps = pStart;
            byte* pe = pEnd;

            using(var iterator = db.NewIterator(
            readOptions: new ReadOptions().SetIterateUpperBound(pe, el)))
            {
                iterator.Seek(ps, sl);

                while(iterator.Valid())
                {
                    var v = (int)iterator.Key()[2];

                    if(v != 6 && v != 7)
                    {
                        Console.Out.WriteLine(v);
                    }

                    iterator.Next();
                }
            }
        }
    }
}
```

**Comment by warrenfalk** [comment] 2017-06-23 13:28
Indeed, the implementation of SetIterateUpperBound is this:
```csharp
        public ReadOptions SetIterateUpperBound(byte[] key)
        {
            iterateUpperBound = key; // necessary because the value will not be copied and so may be gone by the time it is needed
            return SetIterateUpperBound(key, (ulong)key.GetLongLength(0));
        }
```
Note the comment.  What I failed to consider is that not copying the value also means that any internals which take a pointer to it will be broken if the GC moves it.

What I should be doing is allocating native memory, copying there, and freeing it on finalize of the options instance.  And I will look around to see where else this may be an issue.

I was able to reproduce the issue with your code.  Thanks for that.

**Comment by danielcrabtree** [comment] 2017-06-23 14:20
I've always thought you need to assume the GC can relocate unfixed memory at anytime and therefore to be safe, everything needs to be fixed.

With SetIterateUpperBound, the value is used repeatedly over a long time window, so there is a lot of opportunity for it to move and break.

With most other methods, the values are used immediately, creating a very short time window for memory to relocate and break, but a window nonetheless. 

Doesn't this mean fixed is needed everywhere a byte array is passed to RocksDB? If not, when is fixed needed and when not?

**Comment by warrenfalk** [comment] 2017-06-23 14:30
My understanding is that the system will pin any ```byte[]``` passed into a native function until the function returns.  The problem with ```SetIterateUpperBound()``` is that it is internally storing that pointer and using it after the function returns and therefore after it is unpinned.  I first noticed this when the GC would collect the ```byte[]``` and a subsequent call to ```Iterator.Valid()``` would crash (hence the comment in the code).  If this were a problem elsewhere, anything under heavy GC pressure should be crashing fairly frequently.  So I believe it is a stack window issue rather than a time window issue.  Unfortunately, these are harder to find.  In particular RocksDb just isn't very consistent with its handling of the internals, so it is hard to know what memory is owned by whom.

I have the fix coded for the ```SetIterateUpperBound()```.  I'm looking around for other possible instances of the issue.

**Comment by danielcrabtree** [comment] 2017-06-23 15:00
That seems correct. [This answer](https://stackoverflow.com/a/2218540/7905554) explains the behavior nicely:
> Manually pinning of the array becomes necessary if the native code caches the managed pointer.

I take it the only way to figure out which methods besides `SetIterateUpperBound()` cache the pointer is to check the RocksDB code?

**Comment by warrenfalk** [comment] 2017-06-23 15:17
I've scanned the code and haven't found another example.  I did find several potential examples, but they internally copy, unlike ```SetIterateUpperBound()```.  Take for example ```WriteBatch.Put(byte[] key, byte[] value)```.  The values passed into that, if not copied, would cause the same issue, when actually attempting to write the batch to the database, but in fact any modification of the byte array after the call to ```Put()``` has no effect; the original value is what gets written.  So this one copies the value, and this is what I mean by "isn't very consistent".

This is fixed in master.  I'll create a new release shortly.  Note that there's also a pre-release 5.4.6.7 which I want to test more thoroughly before releasing.

**Comment by danielcrabtree** [comment] 2017-06-24 13:25
I've compiled master and run it with my test case and that passes. So it looks good. Thank-you for getting the fix implemented so quickly.

A couple of notes from compiling master:
1. The release build configuration of RocksDbSharpTest needs to allow unsafe code to get it to compile.
2. I'm not sure if you know this, but you can go to project properties / package and then select generate NuGet package on build to have it built automatically.

**Comment by warrenfalk** [comment] 2017-06-24 19:45
Ah, yes, thanks for pointing out allow-unsafe in release.  That's fixed.

It is only just recently that I switched to embedding the package specs in the csproj in place of a separate nuspec.  Doing that, I became aware of the option to generate package on build, but haven't seen a great use for it.  It is certainly possible there's a point to it that I'm missing, but I can easily just request a "pack" at any time, manually, and because the version number doesn't auto-increment in the auto-built package leaving this on can mean accidentally generating a file named MyPackage.1.2.3.nupkg many different times but with different actual versions of the code, which seems needlessly confusing.

**Closed as completed** 2017-06-25 11:54 UTC
